### ISSUE TITLE
When will the arxiv paper be released?

### ISSUE THREAD

**Issue by nonstopfor** [google-research/lm-extraction-benchmark#11]
I wonder when the arxiv paper will be released. I hope to see more details of the data construction process and the performance of current methods.

**Comment by heitikei** [comment]
While you wait, you might consider reading https://arxiv.org/abs/2202.06382?context=cs.CR I found it insightful ://

**Comment by nonstopfor** [comment]
I see in the readme that "We selected 100 total errors because this corresponds to a ~35% recall for existing attacks, leaving significant room for improvement". Does this mean the scores for existing attacks are about 0.35?

**Comment by snoop2head** [comment]
I am also wondering whether the authors are going to release paper regarding the benchmark!

**Comment by carlini** [comment]
Whoops we never closed this, but the paper has been in the github repo for the last month.
