### ISSUE TITLE
Timeline for releasing final leaderboard

### ISSUE THREAD

**Issue by P2333** [google-research/lm-extraction-benchmark#17]
Hi Organizers,

Thank you for your great efforts to organizing the competition. :) The test round deadline has been passed for three weeks, but there has been no further update on the website. Is there a plan or timeline for releasing the final results and leaderboard?

Best,
Tianyu

**Comment by xszheng2020** [comment]
Hi, @P2333 seems the organizers introduced the results on SaTML 2023 https://www.youtube.com/watch?v=IPs7BSNmy5A

<img width="1440" alt="Screenshot 2023-02-25 at 6 27 40 PM" src="https://user-images.githubusercontent.com/101038474/221352025-787e706c-44c3-4ded-a64a-10ae874a8573.png">

**Comment by P2333** [comment]
Thank you 😁
