### ISSUE TITLE
Restrictions on usage of model

### ISSUE THREAD

**Issue by akul-goyal** [google-research/lm-extraction-benchmark#7]
Hi, 

Just wanted to confirm that there are no restrictions on how we [query the model](https://github.com/google-research/lm-extraction-benchmark/blob/a36cbfab1f7719e71667aedc7fbf7f27b57ab823/baseline/simple_baseline.py#L79) ie: the model can only give the confidence on the top n predicted tokens, etc.

**Comment by heitikei** [comment]
@akul-goyal @pluskid 
There are unnecessary restrictions on the query .... creating unnecessary tokens.
It is the first step towards a universal grammar for query programming.

Disable the following (and tidy upstream coding):

https://github.com/google-research/lm-extraction-benchmark/blob/a36cbfab1f7719e71667aedc7fbf7f27b57ab823/baseline/simple_baseline.py#L69

I remain interested.

**Comment by carlini** [comment]
Correct; you can query however you like.

@heitikei I'm sorry I don't understand what you're trying to say. Can you please raise a new issue if there's some problem?
